# Generated by Django 4.1.4 on 2024-03-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcare_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('comments', models.TextField(blank=True)),
                ('doctor', models.CharField(max_length=100)),
            ],
        ),
    ]
