# Generated by Django 4.1.4 on 2024-03-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='cost',
        ),
        migrations.AddField(
            model_name='prescription',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
