# Generated by Django 4.1.4 on 2024-05-01 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0004_remove_appointment_cost_prescription_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(verbose_name='Appointment Date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(verbose_name='Appointment Time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_provider', to=settings.AUTH_USER_MODEL, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='appointments.appointment', verbose_name='Appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date_issued',
            field=models.DateField(auto_now_add=True, verbose_name='Date Issued'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(max_length=255, verbose_name='Dosage'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(verbose_name='Instructions'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication',
            field=models.CharField(max_length=255, verbose_name='Medication'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Prescribed By'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Prescribed To'),
        ),
    ]
