# Generated by Django 4.1.4 on 2024-05-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_address_user_dob_user_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
